# Master config. Edit this file to control the pipeline before each run.

storage:
  base_dir: "."  # Auto-detects current project directory
  videos_dir: "videos"
  assets_dir: "assets"
  scripts_dir: "scripts"
  voiceovers_dir: "voiceovers"
  logs_dir: "logs"
  data_dir: "data"
  jobs_dir: "jobs"

pipeline:
  daily_videos: 1
  video_length_seconds: 420      # target finished length
  tone: "conversational"         # e.g., dramatic, silly, authoritative
  niches: ["ai tools","raspberry pi tips","space trivia"]
  category_ids: [27,28]          # YouTube Education, Science & Tech
  enable_captions: true
  enable_thumbnails: true
  pacing_cooldown_seconds: 60    # sleep between heavy steps

video:
  resolution: "1920x1080"
  fps: 30
  target_bitrate: "4000k"
  codec: "h264"
  preset: "fast"
  crf: 23

llm:
  provider: "ollama"
  model: "phi3:mini"             # default local model
  endpoint: "http://127.0.0.1:11434/api/generate"
  temperature: 0.7
  max_tokens: 1200

asr:
  provider: "whisper_cpp"        # "whisper_cpp" or "openai"
  whisper_cpp_path: "auto"       # Auto-detects whisper-cli location
  model: "auto"                  # Auto-detects model location
  openai_enabled: false

tts:
  provider: "coqui"              # "coqui" or "openai"
  voice: "tts_models/en/ljspeech/tacotron2-DDC"
  rate_wpm: 165
  openai_enabled: false

assets:
  providers:
    - "pixabay"
    - "pexels"
    # - "unsplash"   # Optional; requires UNSPLASH_ACCESS_KEY in .env and attribution
  max_per_section: 3

# Music bed policy configuration
music:
  enabled: true                  # Enable/disable music bed functionality
  library_path: "assets/music"   # Path to music library
  auto_select: true              # Automatically select music based on content
  require_music: false           # Whether music is required for all videos
  fallback_to_silent: true      # Fallback to silent if no music available
  
  # Music selection criteria
  selection:
    bpm_weight: 0.4              # Weight for BPM matching (0.0-1.0)
    mood_weight: 0.4             # Weight for mood matching (0.0-1.0)
    genre_weight: 0.2            # Weight for genre matching (0.0-1.0)
    
  # Audio processing settings
  processing:
    enable_ducking: true         # Enable sidechain ducking
    enable_fades: true           # Enable fade in/out effects
    fade_in_ms: 500             # Fade-in duration in milliseconds
    fade_out_ms: 500            # Fade-out duration in milliseconds
    loop_strategy: "seamless"    # seamless, crossfade, or extend
    
  # Quality and licensing
  quality:
    min_bitrate: "128k"          # Minimum music bitrate
    preferred_formats: ["mp3", "wav", "m4a"]
    require_license_info: true   # Require license information for tracks

render:
  resolution: "1920x1080"
  fps: 30
  music_db: -22                 # Music volume in dB (negative = quieter)
  duck_db: -15                  # Ducking level in dB when VO present
  xfade_ms: 250
  target_bitrate: "4000k"

licenses:
  require_attribution: true

upload:
  auto_upload: false
  visibility: "public"
  schedule: null  # e.g., "2025-08-10T14:00:00Z"

limits:
  max_retries: 2
