storage:
  base_dir: "."  # Auto-detects current project directory
  videos_dir: "videos"
  assets_dir: "assets"
  scripts_dir: "scripts"
  voiceovers_dir: "voiceovers"
  logs_dir: "logs"
  data_dir: "data"
  jobs_dir: "jobs"

pipeline:
  daily_videos: 1
  video_length_seconds: 30
  tone: "helpful"
  niches: ["baby sleep regression tips","parenting advice"]
  category_ids: [27,28]
  enable_captions: true
  enable_thumbnails: true
  pacing_cooldown_seconds: 60

llm:
  provider: "ollama"
  model: "llama3.2:3b"
  endpoint: "http://127.0.0.1:11434/api/generate"
  temperature: 0.7
  max_tokens: 1200

asr:
  provider: "whisper_cpp"
  whisper_cpp_path: "auto"       # Auto-detects whisper-cli location
  model: "auto"                  # Auto-detects model location
  openai_enabled: false

tts:
  provider: "piper"
  voice: "en_US-amy-medium"
  rate_wpm: 165
  ssml: true
  lufs_target: -16.0
  openai_enabled: false

assets:
  providers:
    - "pixabay"
    - "pexels"
    # - "unsplash"  # Uncomment and add UNSPLASH_ACCESS_KEY to .env for attribution-required assets
  max_per_section: 3

# Video pipeline settings
video:
  animatics_only: true            # NEW default - skip stock asset downloads
  enable_legacy_stock: false      # Keep legacy stock path disabled by default
  min_coverage: 0.85              # Minimum scene coverage threshold

licenses:
  require_attribution: true

upload:
  auto_upload: false
  visibility: "public"
  schedule: null

limits:
  max_retries: 2

testing:
  asset_mode: "reuse"               # reuse | live (DEFAULT: reuse for safety)
  fixture_dir: "assets/fixtures"    # where test fixtures are stored
  live_budget_per_run: 5            # hard cap on new downloads in live mode
  live_rate_limit_per_min: 10       # API calls per minute limit in live mode
  fail_on_live_without_keys: true   # fail live tests if API keys missing

# Video rendering settings
render:
  resolution: "1920x1080"
  fps: 30
  music_db: -22
  duck_db: -15
  xfade_ms: 250
  target_bitrate: "4000k"
  codec: "h264_videotoolbox"  # Hardware acceleration
  preset: "fast"  # Encoding speed vs quality trade-off
  crf: 23  # Quality setting (18-28 range, lower = better quality)
  threads: 0  # Auto-detect optimal thread count
  use_hardware_acceleration: true  # Enable/disable hardware acceleration

# Texture and paper feel settings
textures:
  enabled: true                    # Enable/disable texture overlay
  cache_dir: "render_cache/textures"  # Texture cache directory
  session_based: true              # Generate new textures per render session
  
  # Noise settings
  grain:
    density: 0.15                  # Grain density (0.0-1.0)
    scale: 2.0                     # Noise scale factor
    intensity: 0.08                # Grain intensity (0.0-1.0)
    seed_variation: true           # Vary seed per session
  
  # Edge treatment
  edges:
    feather_radius: 1.5            # Edge feathering radius in pixels
    posterization_levels: 8        # Number of posterization levels (2-16)
    edge_strength: 0.3             # Edge detection strength (0.0-1.0)
  
  # Halftone effect
  halftone:
    enabled: true                  # Enable halftone dot pattern
    dot_size: 1.2                  # Halftone dot size in pixels
    dot_spacing: 3.0               # Spacing between dots
    angle: 45                      # Halftone angle in degrees
    intensity: 0.12                # Halftone effect intensity (0.0-1.0)
  
  # Color constraints
  color_preservation: true         # Ensure textures don't introduce new colors
  brand_palette_only: true         # Use only brand palette colors for textures

# Procedural generation settings
procedural:
  seed: 42                          # Random seed for reproducible generation
  max_colors_per_scene: 3           # Maximum distinct colors per scene
  placement:
    min_spacing_px: 64              # Minimum spacing between elements
    safe_margin_px: 40              # Safe margin from scene edges
  motion:
    jitter_ms: 80                   # Motion jitter in milliseconds
