storage:
  base_dir: "."  # Auto-detects current project directory
  videos_dir: "videos"
  assets_dir: "assets"
  scripts_dir: "scripts"
  voiceovers_dir: "voiceovers"
  logs_dir: "logs"
  data_dir: "data"
  jobs_dir: "jobs"

pipeline:
  daily_videos: 1
  video_length_seconds: 420
  tone: "conversational"
  niches: ["ai tools","raspberry pi tips","space trivia"]
  category_ids: [27,28]
  enable_captions: true
  enable_thumbnails: true
  pacing_cooldown_seconds: 60

llm:
  provider: "ollama"
  model: "phi3:mini"
  endpoint: "http://127.0.0.1:11434/api/generate"
  temperature: 0.7
  max_tokens: 1200

asr:
  provider: "whisper_cpp"
  whisper_cpp_path: "auto"       # Auto-detects whisper-cli location
  model: "auto"                  # Auto-detects model location
  openai_enabled: false

tts:
  provider: "coqui"
  voice: "tts_models/en/ljspeech/tacotron2-DDC"
  rate_wpm: 165
  openai_enabled: false

assets:
  providers:
    - "pixabay"
    - "pexels"
  max_per_section: 3

render:
  resolution: "1920x1080"
  fps: 30
  music_db: -22
  duck_db: -15
  xfade_ms: 250
  target_bitrate: "4000k"

licenses:
  require_attribution: true

upload:
  auto_upload: false
  visibility: "public"
  schedule: null

limits:
  max_retries: 2
